FROM golang:1.23-alpine

WORKDIR /app

# Copy go mod file and source
COPY go.mod ./
COPY . .

# Download dependencies
RUN go mod tidy
RUN go mod download

# Build the application
RUN go build -o main cmd/api/main.go

# Expose port
EXPOSE 8080

# Run the application
CMD ["./main"]
